INSERT INTO ENTITIES (ENTITY_NUMBER, SETTINGS, NAME, COUNT, SUB_NUMBER)
    VALUES ('64768874', '{"value1":1,"value2":2,"stringValue":"some_text"}', 'name1', 24, 11111);
INSERT INTO ENTITIES (ENTITY_NUMBER, SETTINGS, NAME, COUNT, SUB_NUMBER)
    VALUES ('12312313', '{"value1":1,"value2":2,"stringValue":"some_text"}', 'name2', 36, 22222);
INSERT INTO ENTITIES (ENTITY_NUMBER, SETTINGS, NAME, COUNT, SUB_NUMBER)
    VALUES ('62187794', '{"value1":1,"value2":2,"stringValue":"some_text"}', 'name3', 48, 33333);

INSERT INTO OTO_ENTITIES (TEXT, ENTITY) VALUES ('OTO1', 1);
INSERT INTO OTO_ENTITIES (TEXT, ENTITY) VALUES ('OTO2', 2);
INSERT INTO OTO_ENTITIES (TEXT, ENTITY) VALUES ('OTO3', 3);

INSERT INTO OTM_ENTITIES (VALUE, OTM_ENTITY_KEY, ENTITY_ID) VALUES (11, 1, 1);
INSERT INTO OTM_ENTITIES (VALUE, OTM_ENTITY_KEY, ENTITY_ID) VALUES (22, 2, 1);
INSERT INTO OTM_ENTITIES (VALUE, OTM_ENTITY_KEY, ENTITY_ID) VALUES (33, 3, 1);
INSERT INTO OTM_ENTITIES (VALUE, OTM_ENTITY_KEY, ENTITY_ID) VALUES (44, 4, 1);
INSERT INTO OTM_ENTITIES (VALUE, OTM_ENTITY_KEY, ENTITY_ID) VALUES (55, 1, 2);

INSERT INTO MTM_ENTITIES (VALUE) VALUES ('aaaaaa');
INSERT INTO MTM_ENTITIES (VALUE) VALUES ('bbbbbb');
INSERT INTO MTM_ENTITIES (VALUE) VALUES ('cccccc');
INSERT INTO MTM_ENTITIES (VALUE) VALUES ('dddddd');

INSERT INTO ENTITY_MTMENTITY (ENTITY_ID, MTMENTITY_ID) VALUES (1, 1);
INSERT INTO ENTITY_MTMENTITY (ENTITY_ID, MTMENTITY_ID) VALUES (1, 2);
INSERT INTO ENTITY_MTMENTITY (ENTITY_ID, MTMENTITY_ID) VALUES (2, 1);
INSERT INTO ENTITY_MTMENTITY VALUES (2, 3);
INSERT INTO ENTITY_MTMENTITY VALUES (2, 4);