DROP TABLE ENTITIES IF EXISTS;
DROP TABLE OTO_ENTITIES IF EXISTS;
DROP TABLE OTM_ENTITIES IF EXISTS;
DROP TABLE MTM_ENTITIES IF EXISTS;
DROP TABLE ENTITY_MTMENTITY IF EXISTS;

CREATE TABLE ENTITIES (
    ID IDENTITY,
    ENTITY_NUMBER VARCHAR(16),
    SETTINGS VARCHAR(240),
    NAME VARCHAR(64),
    COUNT INT,
    SUB_NUMBER INT,
    PRIMARY KEY (ID)
);

CREATE TABLE OTO_ENTITIES (
    ID IDENTITY,
    TEXT VARCHAR(200),
    ENTITY BIGINT
);
ALTER TABLE OTO_ENTITIES
    ADD CONSTRAINT oto_constraint_fk
    FOREIGN KEY (ENTITY)
    REFERENCES ENTITIES (ID);

CREATE TABLE OTM_ENTITIES (
    ID IDENTITY,
    VALUE INT,
    OTM_ENTITY_KEY INT,
    ENTITY_ID BIGINT,
    PRIMARY KEY (ID)
);
ALTER TABLE OTM_ENTITIES
    ADD CONSTRAINT otm_constraint_fk
    FOREIGN KEY (ENTITY_ID)
    REFERENCES ENTITIES (ID);

CREATE TABLE MTM_ENTITIES (
    ID IDENTITY,
    VALUE VARCHAR(48),
    PRIMARY KEY (ID)
);

CREATE TABLE ENTITY_MTMENTITY (
    ENTITY_ID BIGINT,
    MTMENTITY_ID BIGINT,
    PRIMARY KEY (ENTITY_ID, MTMENTITY_ID),
    CONSTRAINT entity_id_fk FOREIGN KEY (ENTITY_ID) REFERENCES ENTITIES (ID),
    CONSTRAINT mtmentity_id_fk FOREIGN KEY (MTMENTITY_ID) REFERENCES MTM_ENTITIES (ID)
);
